apiVersion: v1
kind: Secret
metadata:
  name: food-ordering-secret
  namespace: food-ordering
type: Opaque
stringData:
  mongo-root-username: admin
  mongo-root-password: secure_mongo_password
  jwt-secret: your-super-secret-jwt-key-change-this
  admin-email: jenishchauhan.08@gmail.com
  admin-password: jerry@612
  admin-name: Jenish Chauhan
