apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: food-ordering
spec:
  type: NodePort # 🔥 CHANGE THIS
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30082 # choose any free port (30000–32767)
