apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: food-ordering
data:
  PORT: "5000"
  NODE_ENV: "production"
  FRONTEND_URL: "http://frontend:80,http://admin-panel:80,http://localhost:30080,http://localhost:30081,http://192.168.49.2:30080,http://192.168.49.2:30081"
  MONGO_DATABASE: "jerrys_chaska"
