apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: food-ordering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: jenishchauhan/food-ordering-frontend:latest
          envFrom:
            - configMapRef:
                name: web-config
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
