name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build Images
      - name: Build the Docker backend image
        run: docker build -t jenishchauhan/food-ordering-backend:latest ./backend

      - name: Build the Docker frontend image
        run: |
          docker build \
          --build-arg VITE_API_URL=/api \
          --build-arg VITE_ADMIN_URL=http://localhost:8080 \
          -t jenishchauhan/food-ordering-frontend:latest ./frontend

      - name: Build the admin panel image
        run: docker build --build-arg VITE_API_URL=/api -t jenishchauhan/food-ordering-admin:latest ./admin-panel

      # Login once
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push Images
      - name: Push backend image
        run: docker push jenishchauhan/food-ordering-backend:latest

      - name: Push frontend image
        run: docker push jenishchauhan/food-ordering-frontend:latest

      - name: Push admin image
        run: docker push jenishchauhan/food-ordering-admin:latest
